/*
 * Copyright (C) 2026 Hye Hosting LLC & Hye Ararat contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 */

import type {
  SpiceRuntimeDiagnostics,
  SpiceRuntimePerformanceDiagnostics,
} from './contracts';
import type {
  RuntimeFastPathToggles,
  SessionChannelStatus,
  SessionStage,
  SpiceWorkerDiagnostics,
} from './messages';

export function defaultRuntimeToggles(): RuntimeFastPathToggles {
  return {
    qxlFrameBands: true,
    rawBitmapCoalesce: false,
    artifactSentinel: true,
    presentPacing: true,
    zeroCopyIngress: true,
    gpuUploadReuse: true,
    sharedMemoryBuffers: false,
    browserImageDecode: true,
    browserVideoDecode: false,
    forceWasmDecode: false,
    dropStaleStreamFrames: true,
    revalidateDecode: true,
    revalidateGpu: true,
    revalidatePresent: true,
    disableReadbackFallback: true,
  };
}

export function defaultChannels(): SessionChannelStatus {
  return {
    control: false,
    main: false,
    display: false,
    cursor: false,
    inputs: false,
    playback: false,
    record: false,
    port: false,
    webdav: false,
  };
}

export function emptyPerformanceDiagnostics(
  toggles: RuntimeFastPathToggles = defaultRuntimeToggles(),
): SpiceRuntimePerformanceDiagnostics {
  return {
    firstFrameMs: null,
    avgFrameMs: null,
    lastFrameMs: null,
    avgPacketToPresentMs: null,
    p95PacketToPresentMs: null,
    avgQueueAgeMs: null,
    workerPoolSize: 0,
    activeWorkers: 0,
    peakActiveWorkers: 0,
    queuedTasks: 0,
    peakQueuedTasks: 0,
    decodeQueueDepths: {},
    peakDecodeQueueDepths: {},
    decodeWorkerRestarts: 0,
    canceledDecodeQueuedTasks: 0,
    canceledDecodeInFlightTasks: 0,
    decodeCodecStats: {},
    applyBlockedOnDecode: 0,
    plannerTargetDecodeWorkers: null,
    plannerDecisions: 0,
    pendingMessages: 0,
    pendingChannelBytes: {},
    ingressQueueDepth: 0,
    ingressQueuedBytes: 0,
    ingressBufferedBytes: 0,
    ingressPacketsConsumed: 0,
    ingressBytesConsumed: 0,
    ingressAckCount: 0,
    ingressAckSyncCount: 0,
    avgIngressAckMs: null,
    lastIngressAckMs: null,
    plannedOps: 0,
    canceledQueuedOps: 0,
    canceledInFlightOps: 0,
    droppedLateResults: 0,
    runQueueDepth: 0,
    peakRunQueueDepth: 0,
    laneDepths: {},
    schedulerConcurrency: 0,
    pendingPresentSurfaces: 0,
    lastPresentRectCount: 0,
    lastPresentUploadCount: 0,
    lastPresentUploadArea: 0,
    mergedPresentCount: 0,
    stripedDecodeJobs: 0,
    stripedDecodeTiles: 0,
    directPrimaryUploadCount: 0,
    directPrimaryUploadArea: 0,
    nativePendingBitmapUploads: 0,
    nativePendingBitmapUploadBytes: 0,
    nativeDeferredBitmapUploads: 0,
    nativeDeferredBitmapCommits: 0,
    nativeDeferredBitmapDrops: 0,
    nativeDeferredBitmapPeakUploads: 0,
    nativeDeferredBitmapPeakBytes: 0,
    nativeDeferredBitmapFlushes: 0,
    nativeDeferredBitmapFlushItems: 0,
    nativeDeferredBitmapMaxFlushItems: 0,
    droppedStaleOps: 0,
    dominanceCanceledOps: 0,
    dominanceCanceledArea: 0,
    regionPreemptions: 0,
    oldRegionJobsKilled: 0,
    obsoleteGpuSubmissionsAvoided: 0,
    lateGpuResultsRejected: 0,
    unrelatedRegionsPresentedWhileBlocked: 0,
    wholeScreenBlockCount: 0,
    oldWorkContinuedAfterNewOwner: 0,
    qxlBandMode: 'none',
    qxlBandActive: false,
    qxlBandPendingItems: 0,
    qxlBandsStarted: 0,
    qxlBandsFlushed: 0,
    qxlBandItems: 0,
    qxlBandAvgSize: 0,
    qxlBandMaxSize: 0,
    qxlBandFlushReasons: {},
    qxlBandSentinelTrips: 0,
    qxlBandSentinelUntilMs: null,
    qxlBandStreamSamples: 0,
    qxlBandBitmapStripSamples: 0,
    qxlBandBypassItems: 0,
    packetZeroCopyBodies: 0,
    packetCopiedBodyBytes: 0,
    packetAsyncConcatCount: 0,
    presentCoalescedCount: 0,
    presentUrgentCount: 0,
    nativePresentSkippedForPending: 0,
    presentPacingAvgDelayMs: 0,
    gpuUploadArenaHits: 0,
    gpuUploadArenaMisses: 0,
    gpuBindGroupReuseHits: 0,
    gpuBindGroupReuseMisses: 0,
    batchedBitmapOps: 0,
    batchedBitmapRects: 0,
    presentDebt: 0,
    peakPresentDebt: 0,
    surfaceGenerationSkips: 0,
    regionTokenRejects: 0,
    regionOwnershipEntries: 0,
    regionOwnershipTileBuckets: 0,
    regionOwnershipTileRefs: 0,
    regionOwnershipPrunedEntries: 0,
    regionOwnershipRetainedPlanTokens: 0,
    mutationTicketCommits: 0,
    mutationTicketRejects: 0,
    protocolSideEffectJobs: 0,
    protocolSideEffectJobFailures: 0,
    inputKeyDownSends: 0,
    inputKeyUpSends: 0,
    inputMouseButtonSends: 0,
    avgBatchSize: 0,
    largestBatchSize: 0,
    avgCommitBatchSize: 0,
    largestCommitBatchSize: 0,
    avgMergedDirtyRects: 0,
    decodeCacheHits: 0,
    decodeCacheMisses: 0,
    gpuCacheHits: 0,
    gpuCacheMisses: 0,
    cacheInvalidations: {},
    persistentDecodeCacheHits: 0,
    persistentDecodeCacheMisses: 0,
    persistentDecodeCacheWrites: 0,
    persistentDecodeCacheFailures: 0,
    persistentDecodeCacheStaleDiscards: 0,
    uploadPrepCacheHits: 0,
    uploadPrepCacheMisses: 0,
    cacheEvictionsRam: 0,
    cacheEvictionsVram: 0,
    decodeCacheBytes: 0,
    gpuCacheBytes: 0,
    frameAssemblerPendingOps: 0,
    frameAssemblerCommittedOps: 0,
    frameAssemblerRolledOps: 0,
    noOpApplyRejects: 0,
    cacheMissNoCommit: 0,
    streamOrderedApplies: 0,
    streamFrameDecodeSources: {},
    streamFrameApplySources: {},
    gpuCopyBitsCount: 0,
    cpuCopyBitsFallbackCount: 0,
    gpuSurfaceCopyCount: 0,
    gpuPixelEffectCount: 0,
    presentCanvasSnapshotCount: 0,
    gpuMathOps: 0,
    gpuMathArea: 0,
    gpuComputeOps: 0,
    gpuComputeArea: 0,
    gpuQueueSubmits: 0,
    gpuEmptyQueueSubmits: 0,
    gpuTextureWrites: 0,
    gpuTextureUploadBytes: 0,
    gpuExternalTextureCopies: 0,
    gpuComputeDispatches: 0,
    gpuBitmapComputeDispatches: 0,
    gpuRgbaComputeDispatches: 0,
    gpuRopComputeDispatches: 0,
    gpuRenderPasses: 0,
    gpuPresentRenderPasses: 0,
    cpuPixelMathArea: 0,
    cpuPixelMathReasons: {},
    decodeWaitersCanceled: 0,
    nativeDecodeReady: false,
    nativeDecodeCapabilities: {},
    browserImageDecodeJobs: 0,
    browserVideoDecodeJobs: 0,
    browserDecodeFailures: 0,
    browserDecodeStaleDrops: 0,
    browserDecodeClosedOutputs: 0,
    browserDecodeReadbackFallbacks: 0,
    browserCodecSupport: {},
    webCodecsImageDecoderJobs: 0,
    webCodecsVideoDecoderJobs: 0,
    imageBitmapDecodeJobs: 0,
    displayInitGlzEnabled: false,
    glzDictionaryBytes: 0,
    glzDictionaryEntries: 0,
    glzDictionaryWindowBytes: 0,
    orderingBarriers: 0,
    paletteCacheHits: 0,
    paletteCacheMisses: 0,
    paletteCacheEvictions: 0,
    lzPltDecodeCount: 0,
    gpuPrimaryWriteArea: 0,
    cpuMirrorSyncCount: 0,
    orderedCommandStallMs: 0,
    unsupportedCounts: {},
    displayMessageCounts: {},
    displayEventCounts: {},
    displayErrorCounts: {},
    noCommitReasons: {},
    sharedMemoryRequested: toggles.sharedMemoryBuffers,
    sharedMemoryEligible: false,
    sharedMemoryEnabled: false,
    sharedMemoryDisabledReason: toggles.sharedMemoryBuffers
      ? 'not evaluated'
      : null,
    sharedMemoryBodies: 0,
    sharedMemoryBodyBytes: 0,
    sharedMemoryFallbackCopies: 0,
    sharedDecodeBufferRequests: 0,
    sharedDecodeBufferBytes: 0,
    transferredDecodeBufferBytes: 0,
  };
}

export function createDiagnostics(options: {
  stage?: SessionStage;
  backend?: string;
  preferredBackend?: string;
  graphicsPath?: SpiceRuntimeDiagnostics['displayStack']['graphicsPath'];
  toggles?: RuntimeFastPathToggles;
  webgpu?: boolean;
  webusb?: boolean;
  webdav?: boolean;
  sharedMemory?: boolean;
  trace?: string[];
} = {}): SpiceWorkerDiagnostics {
  const channels = defaultChannels();
  return {
    capabilities: {
      webgpu: options.webgpu ?? false,
      webgl2: false,
      bitmapRenderer: typeof ImageBitmap !== 'undefined',
      offscreen2d: typeof OffscreenCanvas !== 'undefined',
      imageBitmap: typeof createImageBitmap === 'function',
      imageDecoder: typeof (globalThis as { ImageDecoder?: unknown }).ImageDecoder !== 'undefined',
      scheduler: typeof (globalThis as { scheduler?: unknown }).scheduler !== 'undefined',
      webCodecs:
        typeof (globalThis as { VideoDecoder?: unknown }).VideoDecoder !==
        'undefined',
      webUsb: options.webusb ?? false,
      webDav: options.webdav ?? false,
      sharedMemory: options.sharedMemory ?? false,
    },
    backend: options.backend ?? 'native-wasm/webgpu-pending',
    preferredBackend: options.preferredBackend ?? 'webgpu',
    fallbackReason: null,
    rendering: {
      usesOffscreenCanvas: true,
      canvasOwner: 'worker',
      canvasKind: 'offscreen',
      compositorBackend: options.backend ?? 'webgpu-pending',
      primarySurfaceMode: 'gpu-authoritative',
      badge: 'clean-sheet',
      details: 'Native SPICE authority with WebGPU visual pipeline bootstrap.',
    },
    displayStack: {
      graphicsPath: options.graphicsPath ?? 'detecting',
      label: 'Server-grounded SPICE rewrite',
      evidence: [
        'protocol authority in native/WASM',
        'browser JS limited to transport and API bridges',
      ],
    },
    performance: emptyPerformanceDiagnostics(options.toggles),
    audio: {
      mode: 0,
      channels: 0,
      sampleRate: 0,
      multimediaTime: null,
      chunkCount: 0,
      bufferedMs: 0,
      underruns: 0,
      lateChunks: 0,
      volume: null,
      muted: null,
      latencyMs: null,
      sink: 'none',
      channelAttempted: false,
      channelOpen: false,
      socketSource: null,
      unsupportedMode: null,
      contextState: 'none',
    },
    debug: {
      nativeChannels: {},
      channelSockets: {},
      displayPackets: {},
      displayEventFilters: {},
      drawCopyKinds: {},
      drawCopyRops: {},
      recentDisplayOps: [],
      lastDecodedSample: null,
      presentsRequested: 0,
      presentsCompleted: 0,
      lastPresentBackend: null,
      lastPrimarySample: null,
      lastPresentationSample: null,
      lastDrawCopy: null,
    },
    session: {
      stage: options.stage ?? 'idle',
      channels,
      sessionId: null,
      currentMouseMode: null,
      multimediaTime: null,
      lastNotify: null,
      waitCount: 0,
    },
    unsupported: [],
    trace: options.trace ?? [],
  };
}
